from .config import (
    HEADERS,
    PERIOD,
    MIDDLEWARE_SECRET_KEY,
    MIDDLEWARE_URL,
    MIDDLEWARE_ROUTES,
    MIDDLEWARE_ROUTES,
    FIRST_DESCRIPTIVE_FINAL_COST_ADDRESS,
    FIRST_DESCRIPTIVE_FINAL_COST_TITLES,
    SALES_AND_COST_OVER_5_YEARS_ADDRESS,
    SALES_AND_COST_OVER_5_YEARS_TITLES,
    CEMENT_COMPANIES,
    DESCRIPTIVE_TWO_TYPES,
    DESCRIPTIVE_THREE_OVER_HEAD
)
